import React from 'react'

function ERR() {
    const completionMessages = [
        "Please make sure to fill out all the required fields before submitting.",
        "Don't forget to complete all fields before you submit the form.",
        "Ensure that every field is filled in before you proceed with the submission.",
        "Double-check that all necessary fields are filled out prior to submitting.",
        "Your submission won't be complete unless all fields are properly filled.",
        "Remember, all fields must be completed before you can submit the form.",
        "Take a moment to review and fill in any missing fields before submitting.",
        "Submitting the form requires completing all mandatory fields first.",
        "Incomplete fields? Your form submission awaits their completion.",
        "The form can only be submitted after all fields have been filled.",
        "Ready to submit? Ensure every field is filled out to avoid errors.",
        "Missing information? Complete all fields before you hit the submit button.",
        "Submission is just a step away! Fill in any blank fields and you're good to go.",
        "Completeness matters! Your submission needs all fields to be filled.",
        "No shortcuts! Complete all fields before proceeding with the submission.",
        "One last check: have you filled in all fields? Then you're ready to submit.",
        "Almost there! Just make sure no fields are left empty before submitting.",
        "Submission success relies on completing all mandatory fields accurately.",
        "Want to successfully submit? Complete all the required fields first.",
        "Success loves completeness. Fill out all fields before submitting!",
        "Remember: form submission requires filling in all the fields.",
        "Don't rush! Fill in all the fields before submitting the form.",
        "The submit button is waiting for you to complete all the fields.",
        "Check twice, submit once! Complete all the fields before hitting submit.",
        "Proper completion of fields ensures a smooth form submission.",
        "All fields are important! Fill them in before you submit the form.",
        "A complete form is a successful submission. Fill in all fields!",
        "Form submission success begins with field completion. Complete them all!",
        "Don't leave any field behind! Fill them all before you submit.",
        "It's the final step: complete all fields and submit the form.",
        "Your submission is important! Complete all fields to proceed.",
        "Ready to submit? Only if you've filled in all the fields.",
        "A complete form is a happy form. Ensure all fields are filled.",
        "No empty fields allowed! Complete them before you submit.",
        "Check every box: complete all fields before hitting submit.",
        "Completing fields is caring. Care for your submission by completing all fields.",
        "Submit with confidence: all fields are completed and accurate.",
        "Your submission is almost there. Complete the missing fields!",
        "Success demands completeness. Complete all fields before submitting.",
        "Attention to detail matters. Complete all fields before you submit.",
        "The form is ready when all fields are ready. Complete them!",
        "Complete the puzzle: fill in all fields before you submit.",
        "Your form is a masterpiece. Don't forget to fill in all the details!",
        "Form completion unlocked! Fill in all fields to proceed.",
        "Don't let empty fields hold you back. Complete them and submit!",
        "Your submission journey begins with field completion. Complete them all!",
        "A completed form is a work of art. Complete all fields before submitting.",
        "Your form's success story starts with completing all the fields.",
        "The submit button awaits! Complete all fields before clicking.",
        "Success is completing all fields accurately. Then you can submit!",
        "Fields filled? Now you're ready to submit the form.",
        "No field left behind! Complete all fields before submitting.",
        "Complete fields for a complete submission experience.",
        "Success is in the details. Complete all the fields before you submit.",
        "A complete form leads to a successful submission. Fill in all fields!",
        "Don't miss a beat: complete all fields before submitting.",
        "Form submission unlocked: complete all fields and proceed.",
        "Submission greatness achieved by completing all fields.",
        "Fields completed? You're one step closer to submitting the form.",
        "Before submitting, complete all the fields for a successful outcome.",
        "Every field counts. Complete them before you submit.",
        "Ready, set, complete! Fill in all fields before submitting.",
        "Form submission requires a complete field orchestra. Play them all!",
        "Completeness is key. Complete all fields before you submit.",
        "Your form's success is in your hands. Complete all fields!",
        "Almost done! Complete all fields before hitting the submit button.",
        "The final stretch: complete all fields and submit the form.",
        "Success is a fully completed form. Fill in all fields!",
        "Achieve submission nirvana by completing all fields.",
        "Field completion leads to form completion. Complete them all!",
        "Complete fields make for complete submissions. Fill them in!",
        "Don't hold back! Complete all fields before you submit.",
        "A completed form is a happy form. Complete all fields and submit!",
        "Success is just around the corner. Complete all fields and submit!",
        "It's a form completion party! Don't forget to invite all the fields.",
        "No field left unturned! Complete them all before submitting.",
        "Master the art of completion: fill in all fields before submitting.",
        "Form submission glory: complete all fields and achieve success!",
        "Completing fields is your path to form victory. Fill them all!",
        "Submit with pride: complete all fields before hitting the button.",
        "A complete form is a powerful form. Complete all the fields!",
        "Almost ready! Complete all fields for a successful submission.",
        "Form submission excellence: complete all fields and proceed.",
        "Submission satisfaction: complete all fields before hitting submit.",
        "Form completion wizardry: complete all fields like a pro!",
        "Before you submit, ensure all fields are complete and accurate.",
        "Success awaits. Complete all fields before you submit.",
        "No field left untouched! Complete them all for a successful submission.",
        "The form's destiny is in your hands. Complete all fields!",
        "You're just a form completion away from success. Fill in all fields!",
        "Completing fields paves the way for form triumph. Fill them all!",
        "Submission brilliance achieved by completing all fields.",
        "Complete fields lead to a complete form. Fill them in before submitting!",
        "Form completion: engage! Complete all fields and submit.",
        "The finish line is near. Complete all fields and submit triumphantly!",
        "Complete fields for a complete and successful form submission.",
        "Before the grand finale, complete all fields and submit.",
        "Unlock submission power: complete all fields before you submit.",
        "Success is in your hands. Complete all fields and submit!",
        "You're on the right track! Complete all fields for a successful submission.",
        "The magic is in completion: fill in all fields before submitting.",
        "Fields filled, spirits high! Complete them all before you submit.",
        "Form fulfillment achieved by completing all fields.",
        "Complete fields, complete success. Fill them in before submitting!",
        "Achieve submission excellence: complete all fields with care.",
        "Every field is a stepping stone to submission. Complete them all!",
        "Form completion heroics: complete all fields and conquer!",
        "Form submission star: complete all fields and shine brightly!",
        "Completeness breeds success. Complete all fields before you submit!",
        "No field left uncompleted! Fill them all for a successful submission.",
        "Success is built on completion. Complete all fields and submit!",
        "You're almost there! Complete all fields and submit with confidence.",
        "Field by field, completion leads to victory. Complete them all!",
        "Don't skip a beat: complete all fields before you submit the form."
    ];

    return completionMessages[Math.floor(Math.random() * completionMessages.length)];
}

export default ERR