-- Add optional JSONB array of extra project images to gallery.
-- project_srcs stores additional image paths for a gallery item.
-- These are GitHub paths (like /MM_DD_YYYY/id/random.jpg) generated by the
-- admin CLI/server when importing from local files.
--
-- Run this in the Supabase SQL Editor.

ALTER TABLE gallery
  ADD COLUMN IF NOT EXISTS project_srcs jsonb;

